twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_5_layout.html.twig

    # JUSTE UN PETIT TEST SUR LES VARIABLE GLOBALES
    globals:
        #figureRepository: "@App\\Repository\\FigureRepository"

when@test:
    twig:
        strict_variables: true
